SELECT
WO.ASSET_ID,WOC.WORK_ORDER_NO,WOC.ACTUAL_AMOUNT AS "COST_ACTUAL",WOC.EXPENSE_CATEGORY AS "COST_CATEGORY",NULL AS "STOCK_CODE",
NULL AS "TRANSACTION_QUANTITY",NULL AS "TRANSACTION_AMOUNT",NULL AS "EMPLOYEE_NO",NULL AS "TRANSACTION_TYPE",
NULL AS "TRANSACTION_HOURS",NULL AS "COMMITTED_AMOUNT",WO.ASSET_DESC AS "ADDRESS"
FROM SV_WORK_ORDER_COST WOC
JOIN SA_WORK_ORDER WO ON WOC.WORK_ORDER_NO=WO.WORK_ORDER_NO
WHERE WOC.PLANT='04' AND WOC.EXPENSE_CATEGORY IS NOT NULL
AND WOC.WORK_ORDER_NO IS NOT NULL
AND WO.PLANT='04' AND WO.WORK_CATEGORY='MTSET'

UNION

SELECT
AL.ASSET_ID,AL.WORK_ORDER_NO,NULL AS "COST_ACTUAL",NULL AS "COST_CATEGORY",AL.STOCK_CODE,
AL.TRANSACTION_QUANTITY,AL.TRANSACTION_AMOUNT,AL.EMPLOYEE_NO,AL.TRANSACTION_TYPE,
AL.TRANSACTION_HOURS,AL.COMMITTED_AMOUNT,NULL AS "ADDRESS"
FROM SA_ACCOUNT_LOG AL
JOIN SA_WORK_ORDER WO ON AL.WORK_ORDER_NO=WO.WORK_ORDER_NO
WHERE AL.PLANT='04'
AND (AL.TRANSACTION_TYPE IN ('LR','LP') OR AL.STOCK_CODE IN ('PE1PIPE','TRACERWIRE','CSTRACERWIRE'))
AND AL.WORK_ORDER_NO IS NOT NULL AND WO.PLANT='04' AND WO.WORK_CATEGORY='MTSET'

ORDER BY ASSET_ID,WORK_ORDER_NO
 	Kiriyeva, Marina	0 Hrs 0 Mins	0.0	Nov 30, 2021 01:43 PM	Nov 30, 2021 01:43 PM	Here are columns for the report:

(1) ASSET_ID [UMS Location]

(2) WORK_ORDER [SV_WORK_ORDER_COST.WORK_ORDER_NO or SA_ACCOUNT_LOG.WORK_ORDER_NO ]

(3) TRACERWIRE_QUANTITY [WHERE SA_ACCOUNT_LOG.STOCK_CODE='TRACERWIRE' -- need value in SA_ACCOUNT_LOG.TRANSACTION_QUANTITY column ]

(4) CSTRACERWIRE_QUANTITY [WHERE SA_ACCOUNT_LOG.STOCK_CODE='CSTRACERWIRE' -- need value in SA_ACCOUNT_LOG.TRANSACTION_QUANTITY column ]

(5) PE1PIPE_QUANTITY [WHERE SA_ACCOUNT_LOG.STOCK_CODE='PE1PIPE' -- need value in SA_ACCOUNT_LOG.TRANSACTION_QUANTITY column ]

(6) PE2PIPE_QUANTITY [WHERE SA_ACCOUNT_LOG.STOCK_CODE='PE2PIPE' -- need value in SA_ACCOUNT_LOG.TRANSACTION_QUANTITY column ]

(7) PE4PIPE_QUANTITY [WHERE SA_ACCOUNT_LOG.STOCK_CODE='PE4PIPE' -- need value in SA_ACCOUNT_LOG.TRANSACTION_QUANTITY column ]

(8) PE6PIPE_QUANTITY [WHERE SA_ACCOUNT_LOG.STOCK_CODE='PE6PIPE' -- need value in SA_ACCOUNT_LOG.TRANSACTION_QUANTITY column ]

(9) PE58PIPE_QUANTITY [WHERE SA_ACCOUNT_LOG.STOCK_CODE='PE58PIPE' -- need value in SA_ACCOUNT_LOG.TRANSACTION_QUANTITY column ]

(10) PE34PIPE_QUANTITY [WHERE SA_ACCOUNT_LOG.STOCK_CODE='PE34PIPE' -- need value in SA_ACCOUNT_LOG.TRANSACTION_QUANTITY column ]

(11) PE114PIPE_QUANTITY [WHERE SA_ACCOUNT_LOG.STOCK_CODE='PE114PIPE' -- need value in SA_ACCOUNT_LOG.TRANSACTION_QUANTITY column ]

(12) LABOR_OT_COST [WHERE SV_WORK_ORDER_COST.EXPENSE_CATEGORY='Labor-OT' -- need value in SV_WORK_ORDER_COST.ACTUAL_AMOUNT column ]

(13) LABOR_OT_HOURS [WHERE SA_ACCOUNT_LOG.TRANSACTION_TYPE='LP' -- need value in SA_ACCOUNT_LOG.TRANSACTION_HOURS ]

(14) LABOR_REG_COST [WHERE SV_WORK_ORDER_COST.EXPENSE_CATEGORY='Labor-Reg' -- need value in SV_WORK_ORDER_COST.ACTUAL_AMOUNT column ]

(15) LABOR_REG_HOURS [WHERE SA_ACCOUNT_LOG.TRANSACTION_TYPE='LR' -- need value in SA_ACCOUNT_LOG.TRANSACTION_HOURS ]

(16) OTH_STRC_MATL_INV [WHERE SV_WORK_ORDER_COST.EXPENSE_CATEGORY='Oth Strc Matl Inv' -- need value in SV_WORK_ORDER_COST.ACTUAL_AMOUNT column ]

(17) OTH_STRC_CONTRACT [WHERE SV_WORK_ORDER_COST.EXPENSE_CATEGORY='Oth Strc Contract' -- need value in SV_WORK_ORDER_COST.ACTUAL_AMOUNT column ]

(18) RESALE [WHERE SV_WORK_ORDER_COST.EXPENSE_CATEGORY='Resale' -- need value in SV_WORK_ORDER_COST.ACTUAL_AMOUNT column ]

(19) GROUNDS_MATL_INV [WHERE SV_WORK_ORDER_COST.EXPENSE_CATEGORY='Grounds Matl Inv' -- need value in SV_WORK_ORDER_COST.ACTUAL_AMOUNT column ]

(20) OPERATING_SUPPLIES [WHERE SV_WORK_ORDER_COST.EXPENSE_CATEGORY='Operating Supplies' -- need value in SV_WORK_ORDER_COST.ACTUAL_AMOUNT column ]

(21) OTHER_CONTRACTUAL_SVCS [WHERE SV_WORK_ORDER_COST.EXPENSE_CATEGORY='Other Contractual Svcs' -- need value in SV_WORK_ORDER_COST.ACTUAL_AMOUNT column ]

(22) NO_OF_EMPLOYEES [get it from unique number of employees in SA_ACCOUNT_LOG.EMPLOYEE_NO column ]

(23) ADDRESS [SA_WORK_ORDER.ASSET_DESC]